In [1]:
# Numpy stands for numerical python. Since we cannot perform mathematical operations with lists, we need a better tool 
# for mathematical computation and performing mathematical functions 
# What we have is the numpy array. it is similar to the list but has additional features 


In [2]:
#importing numpy 

import numpy as np

   ## 1 Dimensional Array

In [3]:
# The numpy.ndarray is a python datatype just like lists, tuple etc. We can check this by the type() function
#Creating array

array = np.array([1,'hey',2.4,True])
print(array)

['1' 'hey' '2.4' 'True']


In [4]:
# we can see that all the data has been converted to string type 
# This is called as type coercion. i.e all the elements are converted to a single type and the list type is homogeneous. 

array1 = np.array([1,True])
print(array1)

[1 1]


In [6]:
# Adding lists will concatenate them whereas adding numpy array will add them. 

list1 = [1,6,3,5]
list2 = [3,2,6,4]
print(list1 + list2)

np1 = np.array(list1)
np2 = np.array(list2)
print(np1 + np2)


[1, 6, 3, 5, 3, 2, 6, 4]
[4 8 9 9]


In [8]:
# Use boolean indexing to subset numpy arrays

np1 = np.array([11,2,6,34,87,32,9])
np2 = np.array([14,12,66,4,7,33,19])

print(np1>12)  
print(np1[np2>12])  

[False False False  True  True  True False]
[11  6 32  9]


In [10]:
# Exercise
# print names of students whose marks are greater than 70

students = ['sakshi','harsh','swati','venku','aditi','sonam']
np1 = np.array(students)

marks = [80,96,76,48,88,30]
np2 = np.array(marks)

print(np1[np2>70])

['sakshi' 'harsh' 'swati' 'aditi']


 ## 2 Dimensional Array

In [11]:
# Creating 2D array

list_2d = [[1,2,3,4,5,6,7,8],[2,3,4,5,4,8,9,9]]
array_2d = np.array(list_2d)
print(array_2d)

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 4 8 9 9]]


## Attributes of NumPy Array

In [20]:
a = np.array([3,4,12,6,7])


In [21]:
#Get shape
a.shape

(5,)

In [22]:
#Get total no of elements
a.size

5

In [23]:
#Get datatype
a.dtype

dtype('int32')

In [24]:
#to get the data from index
print(a[3])

6


In [25]:
#Get dimension
a.ndim

1

In [26]:
#Get itemsize
a.itemsize

4

In [27]:
#Get totalsize
a.nbytes

20

## Array Indexing and Slicing

In [28]:
a = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(a)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [29]:
#Get the specific element
a[1,0:3]

array([1, 3, 5])

In [30]:
#Get the entire row
a[0]

array([ 2,  4,  6,  8, 10])

In [31]:
#Get the entire column
a[:,4]

array([10,  9])

In [33]:
a[:,2:4]

array([[6, 8],
       [5, 7]])

In [34]:
#We can alse specify as [startindex: stopindex: step]
a[0,1:4:1]

array([4, 6, 8])

In [36]:
#Zeros matrix(0's)
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#Ones matrix(1's)
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
#Any other number
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [41]:
#Getting an array with dimensions similar to any other array
b = np.full_like(a,4)
print(b)

[[4 4 4 4 4]
 [4 4 4 4 4]]


In [42]:
#Get identity matrix
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [45]:
#Repeat an array
arr = np.array([[1,2,3]])
np.repeat(arr,3,axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [3]:
#Getting numbers greater or smaller than a particular number
a = np.array([13,56,32,6,7,22,77])
print(a[a>20])
print(a[a<20])

[56 32 22 77]
[13  6  7]


In [4]:
#Getting min and max of array
print(a.min())
print(a.max())


6
77


In [9]:
#Calculating mean and sum of array
print(a.sum())
print(a.mean())

213
30.428571428571427


## How to copy an array

In [8]:
arr = np.array([32,56,77,23])
copy_arr = arr.copy()
print(copy_arr)

[32 56 77 23]


## Reshaping

In [12]:
var = np.arange(32).reshape(8,4)
print(var)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


## Transposing Array

In [13]:
print(var)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [14]:
var.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

## Sorting


In [17]:
varr = [23,65,2,6,33,77,89,5]
print(varr)
varr.sort()
print(varr)

[23, 65, 2, 6, 33, 77, 89, 5]
[2, 5, 6, 23, 33, 65, 77, 89]


## String Functions

In [22]:
name = ['akshita','vimal','shikha']
sirname = ['SHARMA','MISHRA',"SINGH"]

In [23]:
#Changing the first letter to capital
np.char.capitalize(name)

array(['Akshita', 'Vimal', 'Shikha'], dtype='<U7')

In [25]:
#changing names to upper case
np.char.upper(name)

array(['AKSHITA', 'VIMAL', 'SHIKHA'], dtype='<U7')

In [26]:
#changing sirname to lower case
np.char.lower(sirname)

array(['sharma', 'mishra', 'singh'], dtype='<U6')